### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Rian501** [nss-day-cohort-20/group-project-theme-park-2-gitbearified#27]
basic styling for functionality:
- [x] border classes for map
- [x] attraction descriptions (fake links)
- [x]  attraction descriptions inline display,
- [x]  attraction descriptions show/hide
- [x] logo
- [x] footer
- [x] bootstrap grid for map

**Comment by Rian501** [comment]
- [ ] make it look baller awesomesauce

**Comment by mozecode** [comment]
On attraction descriptions, we still need to do inline display in the park info aside.  Also need to style footer fully.
